language: node_js
node_js:
- '0.10'
branches:
  only:
    - master
    - develop
before_install:
- openssl aes-256-cbc -K $encrypted_3d066665149a_key -iv $encrypted_3d066665149a_iv
  -in gcloudauth.json.enc -out gcloudauth.json -d
- npm install -g grunt-cli
- npm install -g bower
- npm install -g tsd
install:
- npm install
- tsd update
- if [[ ! -f google-cloud-sdk/path.bash.inc ]]; then echo "Downloading google cloud
  sdk"; wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip; unzip
  -qq google-cloud-sdk.zip; google-cloud-sdk/install.sh --usage-reporting false --path-update
  false --rc-path=~/.bashrc --bash-completion false --override-components=app; fi;
- google-cloud-sdk/bin/gcloud config set component_manager/fixed_sdk_version 0.9.56
- google-cloud-sdk/bin/gcloud components update preview app --quiet
before_script:
- bower install
- grunt travis-build -v
after_success:
- "./travis-ci-deploy.sh"
