language: node_js
node_js:
- '0.10'
branches:
  only:
    - master
    - develop
script:
- npm run build
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./travis-ci-deploy.sh || false'
sudo: false
cache:
  directories:
    - node_modules
