runtime: go
api_version: go1

handlers:
- url: /scripts
  static_dir: dist/scripts

- url: /styles
  static_dir: dist/styles

- url: /images
  static_dir: dist/images

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html