runtime: go
api_version: go1

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /.*
  static_files: index.html
  upload: index.html